version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: python-it
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
